server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=development;encrypt=true;trustServerCertificate=true;
    username: sa
    password: D@vid123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2016Dialect
      ddl-auto: update